export const en = {
  nav: {
    work: "Work",
    about: "About",
    contact: "Connect",
  },
  hero: {
    eyebrow: "PORTFOLIO / 2026",
    headline: "I build at the point where product, AI, code, and visual storytelling meet.",
    role: "AI Product Builder & Creative Technologist",
    body: "I turn rough ideas into mobile products, AI systems, generative video, and things that leave the screen as physical objects.",
    ctaPrimary: "Selected work",
    ctaSecondary: "Copy email",
    emailCopied: "Copied",
  },
  toolsMarquee: {
    eyebrow: "Tools I work with",
  },
  orbit: {
    worlds: {
      "3d": "3D",
      video: "Video Creator",
      developers: "Developer",
    },
    worldTagline: {
      "3d": "Blender, Cinema 4D, 3ds Max: modeled, sliced, and printed for real.",
      video: "Storyboards, generative pipelines, and Remotion delivery.",
      developers: "Apps, websites, and AI automation, from no-code to full-code.",
    },
    back: "Back",
    prevLabel: "Previous world",
    nextLabel: "Next world",
    viewProject: "View case study",
    comingSoon: "More work landing here soon",
    switchWorld: "Switch world",
    spin: "Spin the reel",
  },
  extraWork: {
    games: {
      label: "Game Dev",
      tagline: "Interactive builds and playable experiments — landing here as they ship.",
    },
    aiCreator: {
      label: "AI Creator",
      tagline: "Clips made entirely with generative AI — no camera, no crew.",
    },
  },
  figurines: {
    sectionTitle: "Prints",
    filament: "Filament",
    printTime: "Print time",
    material: "Material",
    printer: "Printer",
  },
  bioCard: {
    age: "31",
    experiences: [
      {
        title: "Project Manager",
        description: "Scoping fuzzy ideas into shippable plans: one clear outcome, a path to release, and a scope kept honest.",
      },
      {
        title: "Middle AI Developer",
        description: "Building mobile & web products with AI at the core — Gemini/Claude integrations, prompt systems, server-side proxies.",
      },
      {
        title: "Video Creator",
        description: "Structured AI video pipelines — brief to storyboard to Remotion render, with a real delivery pass.",
      },
      {
        title: "3D Modelling + Print",
        description: "From a Blender model to a sliced file to a print that actually has to hold together.",
      },
    ],
    explore: "Explore work",
  },
  connect: {
    cta: "Let's connect",
    telegram: "Telegram",
    email: "Email",
    twitter: "Twitter",
  },
  gridScroll: {
    toggle: "Grid scroll",
    speed: "Speed",
  },
  theme: {
    switchToLight: "Switch to light theme",
    switchToDark: "Switch to dark theme",
  },
  developersFilter: {
    all: "All",
    apps: "Apps",
    websites: "Websites",
    games: "Games",
  },
  videoWorld: {
    videosComingSoon: "Categorized videos landing here soon.",
    uncategorized: "Other",
    categories: {
      events: "Events",
      interview: "Interview",
      promo: "Promo",
      realisticCinematic: "Realistic Cinematic",
      viralVideo: "Viral Video",
    },
    viewAll: "View all clips →",
    allClips: "The full reel for this category.",
  },
  videoPlayer: {
    play: "Play",
    pause: "Pause",
    mute: "Mute",
    unmute: "Unmute",
    volume: "Volume",
    fullscreen: "Fullscreen",
    close: "Close",
  },
  rail: {
    label: "Across layers",
    nodes: [
      { id: "product", label: "PRODUCT", proof: "Feature scope that holds up past the happy path" },
      { id: "mobile", label: "MOBILE", proof: "Native-feeling apps built in Expo, backed by Supabase" },
      { id: "ai", label: "AI", proof: "A primary model with a backup that kicks in automatically" },
      { id: "video", label: "VIDEO", proof: "One brief becomes a finished video, not a raw generation" },
      { id: "3d", label: "3D", proof: "A model that has to survive being sliced and printed" },
      { id: "automation", label: "AUTOMATION", proof: "Work that runs on a webhook, not a to-do list" },
      { id: "deploy", label: "DEPLOY", proof: "Self-hosted infrastructure, not a managed platform" },
    ],
  },
  selectedWork: {
    title: "My work",
    intro: "Different mediums. One instinct: find the hard part, build the system, iterate until it holds together.",
    openCaseStudy: "Open case study",
    view: "View",
    roleLabel: "Role",
    stackLabel: "Stack",
  },
  caseStudy: {
    hardPart: "The hard part",
    summary: "Overview",
    approach: "Approach",
    demo: "Walkthrough",
    verificationNote: "Verification note",
    gallery: "Screenshots",
  },
  metaverse: {
    cta: "3D View",
    loopLabel: "Physical iteration loop",
    title: "The Print Room",
    tagline: "A light room built to hold every physical print as it ships — fly the camera around, empty pedestals for now.",
    empty: "Nothing on the shelves yet — check back once a print ships.",
    webglFallback: "This room needs WebGL — try a different browser or device to fly the camera through it.",
  },
  capabilities: {
    eyebrow: "CAPABILITIES",
    title: "Seven areas, and the real tools behind each one.",
    groups: [
      {
        label: "Decisions that don't show up in a screenshot",
        items: ["Feature architecture", "Onboarding thinking", "Monetization boundaries", "Release readiness", "Iterative feedback"],
      },
      {
        label: "Where the tap becomes a database write",
        items: ["Expo / React Native", "TypeScript", "Navigation", "OTA updates", "Supabase", "Widgets"],
      },
      {
        label: "AI that keeps working when the model doesn't",
        items: ["Claude", "Gemini", "Structured outputs", "Fallback logic", "Server-side proxy", "Vision & voice"],
      },
      {
        label: "Generated footage, edited like real footage",
        items: ["Veo / Kling", "Storyboards", "Continuity", "Shot design", "Remotion", "AI music workflows"],
      },
      {
        label: "The parts I don't do by hand anymore",
        items: ["Supabase Edge Functions", "Cloudflare Workers", "Webhooks", "Telegram bots"],
      },
      {
        label: "Getting it live is part of the job, not someone else's problem",
        items: ["GitHub", "Coolify", "Hetzner", "Cloudflare", "Push-to-deploy"],
      },
      {
        label: "Modeling doesn't end until the print does",
        items: ["Blender", "Cinema 4D", "3ds Max", "FDM printing", "Bambu Studio", "Physical iteration"],
      },
    ],
  },
  workflow: {
    eyebrow: "MY OPERATING SYSTEM",
    title: "My operating system",
    intro: "Fast does not have to mean careless. I use AI agents aggressively, not blindly. I keep the work grounded in project context, real constraints, review, and deployment.",
    stages: [
      { index: "01", title: "Find the real problem", body: "I reduce a vague idea to one useful user action and one clear outcome." },
      { index: "02", title: "Build the system, not only the screen", body: "I map data, states, edge cases, AI behavior, backend boundaries, and the path to deployment." },
      { index: "03", title: "Let agents execute, keep the judgment calls", body: "Claude Code and Codex handle the mechanical parts — scaffolding, repetitive edits, boilerplate. Every change still gets reviewed against project memory and constraints before it ships." },
      { index: "04", title: "Iterate in public reality", body: "Real devices, real API limits, weird edge cases, store requirements, broken generations, and failed prints are part of the process." },
      { index: "05", title: "Ship, observe, refine", body: "Push, deploy, test, collect feedback, fix what matters, repeat." },
    ],
  },
  agentNative: {
    eyebrow: "AGENT-NATIVE, PRODUCT-LED",
    title: "Agent-native, product-led",
    body: "Every change follows the loop below: an intent, project memory, one agent turn, a check on a real device or browser, then Git and deploy. Feedback from that becomes the next intent.",
    loop: ["INTENT", "PROJECT MEMORY", "AGENT", "IMPLEMENTATION", "REVIEW", "REAL DEVICE / BROWSER", "GIT", "DEPLOY", "FEEDBACK"],
  },
  about: {
    eyebrow: "ABOUT",
    title: "About",
    body: [
      "I'm Serhii, a builder based in Kyiv. I move between AI products, mobile apps, video, automation, and 3D, depending on where the problem takes me.",
      "Most of what I know, I picked up by actually building things: figuring out the UX, wiring up Supabase, turning a camera into an AI-powered workflow, or taking a model from Blender to a real, physical print.",
      "What ties it all together is pretty simple — I like taking a messy idea and turning it into something that actually works.",
    ],
  },
  contact: {
    eyebrow: "CONTACT",
    title: "Have a hard idea? Good.",
    body: "This is where I do my best work: product, AI, creative technology, fast execution.",
    ctaPrimary: "Email me",
    ctaSecondary: "Copy email",
    availability: "Open to strong product, AI and creative-tech opportunities",
  },
  footer: {
    rights: "All rights reserved.",
  },
  status: {
    shipped: "SHIPPED",
    "in-testing": "IN TESTING",
    prototype: "PROTOTYPE",
    concept: "CONCEPT",
    "client-work": "CLIENT WORK",
    "system-design": "SYSTEM DESIGN",
    experiment: "EXPERIMENT",
  },
  notFound: {
    title: "Page not found",
    body: "This page does not exist, or the idea behind it never shipped.",
    cta: "Back home",
  },
  aiAgent: {
    openLabel: "Ask about Serhii",
    closeLabel: "Close chat",
    title: "Ask about Serhii",
    subtitle: "Grounded in his real skills and projects — not a generic chatbot.",
    greeting: "Hi! Ask me anything about Serhii's skills, background, or projects.",
    placeholder: "Ask a question...",
    send: "Send",
    thinking: "Thinking...",
    errorMessage: "Something went wrong — try again in a moment.",
    unknownFallback: "I don't have that detail on hand — I'll check with Serhii and get back to you.",
    voiceCall: {
      startLabel: "Start a voice call",
      bannerLabel: "Call the agent — learn more about Serhii",
      modalTitle: "Voice call",
      modalSubtitle: "Talk to an agent grounded in Serhii's real skills and projects. Capped at 2 minutes.",
      emailPrompt: "Enter your email so Serhii can follow up if needed.",
      emailPlaceholder: "you@email.com",
      emailInvalid: "Enter a valid email address.",
      emailContinue: "Continue",
      verifying: "Verifying you're human...",
      connecting: "Connecting...",
      listening: "Listening...",
      speaking: "Speaking...",
      wrappingUp: "Wrapping up — the call ends soon.",
      finished: "Call ended.",
      hangUp: "Hang up",
      close: "Close",
      tryAgain: "Try again",
      micDenied: "Microphone access is needed for a voice call — allow it in your browser and try again.",
      connectionError: "Couldn't connect — try again in a moment.",
      verificationError: "Verification failed — refresh the page and try again.",
      rateLimitedError: "Too many calls right now — try again later.",
      notConfigured: "Voice call isn't set up yet.",
    },
  },
};
